<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../MemoryProfiler.Contracts/MemoryProfiler.Contracts.csproj" />
    <ProjectReference Include="../MemoryProfiler.Analysis/MemoryProfiler.Analysis.csproj" />
    <ProjectReference Include="../MemoryProfiler.Storage/MemoryProfiler.Storage.csproj" />
  </ItemGroup>
</Project>
